@ProjectTraidingDiagnostics_HostAddress = http://localhost:5190

GET {{ProjectTraidingDiagnostics_HostAddress}}/todos/
Accept: application/json

###

GET {{ProjectTraidingDiagnostics_HostAddress}}/todos/1
Accept: application/json

###
