namespace ProjectTraiding.Moex.Series;

public static class MoexSeriesRegistry
{
    public static readonly MoexSeriesSpec TradeStatsStock = new()
    {
        DataKind = "tradestats",
        Market = "stock",
        TelemetryDataKind = "tradestats",
        MethodTemplate = "/datashop/algopack/eq/tradestats/{0}.json",
        RootKey = "data",
        SourceColumns =
        [
            new(0, "tradedate"u8.ToArray(), ColumnKind.String),
            new(1, "tradetime"u8.ToArray(), ColumnKind.String),
            new(2, "secid"u8.ToArray(), ColumnKind.String),
            new(3, "pr_open"u8.ToArray(), ColumnKind.Double),
            new(4, "pr_high"u8.ToArray(), ColumnKind.Double),
            new(5, "pr_low"u8.ToArray(), ColumnKind.Double),
            new(6, "pr_close"u8.ToArray(), ColumnKind.Double),
            new(7, "pr_std"u8.ToArray(), ColumnKind.Double),
            new(8, "vol"u8.ToArray(), ColumnKind.Int32),
            new(9, "val"u8.ToArray(), ColumnKind.Double),
            new(10, "trades"u8.ToArray(), ColumnKind.Int32),
            new(11, "pr_vwap"u8.ToArray(), ColumnKind.Double),
            new(12, "pr_change"u8.ToArray(), ColumnKind.Double),
            new(13, "trades_b"u8.ToArray(), ColumnKind.Int32),
            new(14, "trades_s"u8.ToArray(), ColumnKind.Int32),
            new(15, "val_b"u8.ToArray(), ColumnKind.Double),
            new(16, "val_s"u8.ToArray(), ColumnKind.Double),
            new(17, "vol_b"u8.ToArray(), ColumnKind.Int64),
            new(18, "vol_s"u8.ToArray(), ColumnKind.Int64),
            new(19, "disb"u8.ToArray(), ColumnKind.Double),
            new(20, "pr_vwap_b"u8.ToArray(), ColumnKind.Double),
            new(21, "pr_vwap_s"u8.ToArray(), ColumnKind.Double),
            new(22, "SYSTIME"u8.ToArray(), ColumnKind.DateTime),
            new(23, "sec_pr_open"u8.ToArray(), ColumnKind.Int32),
            new(24, "sec_pr_high"u8.ToArray(), ColumnKind.Int32),
            new(25, "sec_pr_low"u8.ToArray(), ColumnKind.Int32),
            new(26, "sec_pr_close"u8.ToArray(), ColumnKind.Int32),
        ],
        Table = "moex_trade_stats_5m_stock",
        TargetColumns =
        [
            new("secid", "LowCardinality(String)", FillRule.TaskSecId, Required: true,
                RequiredMessage: "Загрузка статистики сделок отвергнута: secid пустой."),
            new("source_time", "DateTime64(3, 'Europe/Moscow')", FillRule.SourceDateTime, 0, 1, Required: true),
            new("pr_open", "Nullable(Float64)", FillRule.Direct, 3),
            new("pr_high", "Nullable(Float64)", FillRule.Direct, 4),
            new("pr_low", "Nullable(Float64)", FillRule.Direct, 5),
            new("pr_close", "Nullable(Float64)", FillRule.Direct, 6),
            new("pr_std", "Nullable(Float64)", FillRule.Direct, 7),
            new("vol", "Nullable(Int32)", FillRule.Direct, 8),
            new("val", "Nullable(Float64)", FillRule.Direct, 9),
            new("trades", "Nullable(Int32)", FillRule.Direct, 10),
            new("pr_vwap", "Nullable(Float64)", FillRule.Direct, 11),
            new("pr_change", "Nullable(Float64)", FillRule.Direct, 12),
            new("trades_b", "Nullable(Int32)", FillRule.Direct, 13),
            new("trades_s", "Nullable(Int32)", FillRule.Direct, 14),
            new("val_b", "Nullable(Float64)", FillRule.Direct, 15),
            new("val_s", "Nullable(Float64)", FillRule.Direct, 16),
            new("vol_b", "Nullable(Int64)", FillRule.Direct, 17),
            new("vol_s", "Nullable(Int64)", FillRule.Direct, 18),
            new("disb", "Nullable(Float64)", FillRule.Direct, 19),
            new("pr_vwap_b", "Nullable(Float64)", FillRule.Direct, 20),
            new("pr_vwap_s", "Nullable(Float64)", FillRule.Direct, 21),
            new("sec_pr_open", "Nullable(Int32)", FillRule.Direct, 23),
            new("sec_pr_high", "Nullable(Int32)", FillRule.Direct, 24),
            new("sec_pr_low", "Nullable(Int32)", FillRule.Direct, 25),
            new("sec_pr_close", "Nullable(Int32)", FillRule.Direct, 26),
            new("systime", "Nullable(DateTime64(3, 'Europe/Moscow'))", FillRule.WallClock, 22),
        ],
        TokenPrefix = "tradestats:5m:stock",
        Pagination = PaginationKind.Cursor,
        RequestKey = RequestKeyRule.TaskSecId,
    };

    public static readonly MoexSeriesSpec TradeStatsFutures = new()
    {
        DataKind = "tradestats",
        Market = "futures",
        TelemetryDataKind = "tradestats",
        MethodTemplate = "/datashop/algopack/fo/tradestats/{0}.json",
        RootKey = "data",
        SourceColumns =
        [
            new(0, "tradedate"u8.ToArray(), ColumnKind.String),
            new(1, "tradetime"u8.ToArray(), ColumnKind.String),
            new(2, "secid"u8.ToArray(), ColumnKind.String),
            new(3, "asset_code"u8.ToArray(), ColumnKind.String),
            new(4, "pr_open"u8.ToArray(), ColumnKind.Double),
            new(5, "pr_high"u8.ToArray(), ColumnKind.Double),
            new(6, "pr_low"u8.ToArray(), ColumnKind.Double),
            new(7, "pr_close"u8.ToArray(), ColumnKind.Double),
            new(8, "pr_std"u8.ToArray(), ColumnKind.Double),
            new(9, "vol"u8.ToArray(), ColumnKind.Int64),
            new(10, "val"u8.ToArray(), ColumnKind.Int64),
            new(11, "trades"u8.ToArray(), ColumnKind.Int32),
            new(12, "pr_vwap"u8.ToArray(), ColumnKind.Double),
            new(13, "pr_change"u8.ToArray(), ColumnKind.Double),
            new(14, "trades_b"u8.ToArray(), ColumnKind.Int32),
            new(15, "trades_s"u8.ToArray(), ColumnKind.Int32),
            new(16, "val_b"u8.ToArray(), ColumnKind.Double),
            new(17, "val_s"u8.ToArray(), ColumnKind.Double),
            new(18, "vol_b"u8.ToArray(), ColumnKind.Int64),
            new(19, "vol_s"u8.ToArray(), ColumnKind.Int64),
            new(20, "disb"u8.ToArray(), ColumnKind.Double),
            new(21, "pr_vwap_b"u8.ToArray(), ColumnKind.Double),
            new(22, "pr_vwap_s"u8.ToArray(), ColumnKind.Double),
            new(23, "im"u8.ToArray(), ColumnKind.Double),
            new(24, "oi_open"u8.ToArray(), ColumnKind.Int64),
            new(25, "oi_high"u8.ToArray(), ColumnKind.Int64),
            new(26, "oi_low"u8.ToArray(), ColumnKind.Int64),
            new(27, "oi_close"u8.ToArray(), ColumnKind.Int64),
            new(28, "sec_pr_open"u8.ToArray(), ColumnKind.Int32),
            new(29, "sec_pr_high"u8.ToArray(), ColumnKind.Int32),
            new(30, "sec_pr_low"u8.ToArray(), ColumnKind.Int32),
            new(31, "sec_pr_close"u8.ToArray(), ColumnKind.Int32),
            new(32, "SYSTIME"u8.ToArray(), ColumnKind.DateTime),
        ],
        Table = "moex_trade_stats_5m_futures",
        TargetColumns =
        [
            new("secid", "LowCardinality(String)", FillRule.TaskSecId, Required: true,
                RequiredMessage: "Загрузка статистики сделок отвергнута: secid пустой."),
            new("source_time", "DateTime64(3, 'Europe/Moscow')", FillRule.SourceDateTime, 0, 1, Required: true),
            new("asset_code", "LowCardinality(Nullable(String))", FillRule.Direct, 3),
            new("pr_open", "Nullable(Float64)", FillRule.Direct, 4),
            new("pr_high", "Nullable(Float64)", FillRule.Direct, 5),
            new("pr_low", "Nullable(Float64)", FillRule.Direct, 6),
            new("pr_close", "Nullable(Float64)", FillRule.Direct, 7),
            new("pr_std", "Nullable(Float64)", FillRule.Direct, 8),
            new("vol", "Nullable(Int64)", FillRule.Direct, 9),
            new("val", "Nullable(Int64)", FillRule.Direct, 10),
            new("trades", "Nullable(Int32)", FillRule.Direct, 11),
            new("pr_vwap", "Nullable(Float64)", FillRule.Direct, 12),
            new("pr_change", "Nullable(Float64)", FillRule.Direct, 13),
            new("trades_b", "Nullable(Int32)", FillRule.Direct, 14),
            new("trades_s", "Nullable(Int32)", FillRule.Direct, 15),
            new("val_b", "Nullable(Float64)", FillRule.Direct, 16),
            new("val_s", "Nullable(Float64)", FillRule.Direct, 17),
            new("vol_b", "Nullable(Int64)", FillRule.Direct, 18),
            new("vol_s", "Nullable(Int64)", FillRule.Direct, 19),
            new("disb", "Nullable(Float64)", FillRule.Direct, 20),
            new("pr_vwap_b", "Nullable(Float64)", FillRule.Direct, 21),
            new("pr_vwap_s", "Nullable(Float64)", FillRule.Direct, 22),
            new("im", "Nullable(Float64)", FillRule.Direct, 23),
            new("oi_open", "Nullable(Int64)", FillRule.Direct, 24),
            new("oi_high", "Nullable(Int64)", FillRule.Direct, 25),
            new("oi_low", "Nullable(Int64)", FillRule.Direct, 26),
            new("oi_close", "Nullable(Int64)", FillRule.Direct, 27),
            new("sec_pr_open", "Nullable(Int32)", FillRule.Direct, 28),
            new("sec_pr_high", "Nullable(Int32)", FillRule.Direct, 29),
            new("sec_pr_low", "Nullable(Int32)", FillRule.Direct, 30),
            new("sec_pr_close", "Nullable(Int32)", FillRule.Direct, 31),
            new("systime", "Nullable(DateTime64(3, 'Europe/Moscow'))", FillRule.WallClock, 32),
        ],
        TokenPrefix = "tradestats:5m:futures",
        Pagination = PaginationKind.Cursor,
        RequestKey = RequestKeyRule.TaskSecId,
    };

    public static readonly MoexSeriesSpec ObStatsStock = new()
    {
        DataKind = "obstats",
        Market = "stock",
        TelemetryDataKind = "obstats",
        MethodTemplate = "/datashop/algopack/eq/obstats/{0}.json",
        RootKey = "data",
        SourceColumns =
        [
            new(0, "tradedate"u8.ToArray(), ColumnKind.String),
            new(1, "tradetime"u8.ToArray(), ColumnKind.String),
            new(2, "secid"u8.ToArray(), ColumnKind.String),
            new(3, "spread_bbo"u8.ToArray(), ColumnKind.Double),
            new(4, "spread_lv10"u8.ToArray(), ColumnKind.Double),
            new(5, "spread_1mio"u8.ToArray(), ColumnKind.Double),
            new(6, "levels_b"u8.ToArray(), ColumnKind.Int32),
            new(7, "levels_s"u8.ToArray(), ColumnKind.Int32),
            new(8, "vol_b"u8.ToArray(), ColumnKind.Int64),
            new(9, "vol_s"u8.ToArray(), ColumnKind.Int64),
            new(10, "val_b"u8.ToArray(), ColumnKind.Int64),
            new(11, "val_s"u8.ToArray(), ColumnKind.Int64),
            new(12, "imbalance_vol_bbo"u8.ToArray(), ColumnKind.Double),
            new(13, "imbalance_val_bbo"u8.ToArray(), ColumnKind.Double),
            new(14, "imbalance_vol"u8.ToArray(), ColumnKind.Double),
            new(15, "imbalance_val"u8.ToArray(), ColumnKind.Double),
            new(16, "vwap_b"u8.ToArray(), ColumnKind.Double),
            new(17, "vwap_s"u8.ToArray(), ColumnKind.Double),
            new(18, "vwap_b_1mio"u8.ToArray(), ColumnKind.Double),
            new(19, "vwap_s_1mio"u8.ToArray(), ColumnKind.Double),
            new(20, "SYSTIME"u8.ToArray(), ColumnKind.DateTime),
        ],
        Table = "moex_ob_stats_5m_stock",
        TargetColumns =
        [
            new("secid", "LowCardinality(String)", FillRule.TaskSecId, Required: true,
                RequiredMessage: "Загрузка статистики стакана отвергнута: secid пустой."),
            new("source_time", "DateTime64(3, 'Europe/Moscow')", FillRule.SourceDateTime, 0, 1, Required: true),
            new("spread_bbo", "Nullable(Float64)", FillRule.Direct, 3),
            new("spread_lv10", "Nullable(Float64)", FillRule.Direct, 4),
            new("spread_1mio", "Nullable(Float64)", FillRule.Direct, 5),
            new("levels_b", "Nullable(Int32)", FillRule.Direct, 6),
            new("levels_s", "Nullable(Int32)", FillRule.Direct, 7),
            new("vol_b", "Nullable(Int64)", FillRule.Direct, 8),
            new("vol_s", "Nullable(Int64)", FillRule.Direct, 9),
            new("val_b", "Nullable(Int64)", FillRule.Direct, 10),
            new("val_s", "Nullable(Int64)", FillRule.Direct, 11),
            new("imbalance_vol_bbo", "Nullable(Float64)", FillRule.Direct, 12),
            new("imbalance_val_bbo", "Nullable(Float64)", FillRule.Direct, 13),
            new("imbalance_vol", "Nullable(Float64)", FillRule.Direct, 14),
            new("imbalance_val", "Nullable(Float64)", FillRule.Direct, 15),
            new("vwap_b", "Nullable(Float64)", FillRule.Direct, 16),
            new("vwap_s", "Nullable(Float64)", FillRule.Direct, 17),
            new("vwap_b_1mio", "Nullable(Float64)", FillRule.Direct, 18),
            new("vwap_s_1mio", "Nullable(Float64)", FillRule.Direct, 19),
            new("systime", "Nullable(DateTime64(3, 'Europe/Moscow'))", FillRule.WallClock, 20),
        ],
        TokenPrefix = "obstats:5m:stock",
        Pagination = PaginationKind.Cursor,
        RequestKey = RequestKeyRule.TaskSecId,
    };

    public static readonly MoexSeriesSpec ObStatsFutures = new()
    {
        DataKind = "obstats",
        Market = "futures",
        TelemetryDataKind = "obstats",
        MethodTemplate = "/datashop/algopack/fo/obstats/{0}.json",
        RootKey = "data",
        SourceColumns =
        [
            new(0, "tradedate"u8.ToArray(), ColumnKind.String),
            new(1, "tradetime"u8.ToArray(), ColumnKind.String),
            new(2, "secid"u8.ToArray(), ColumnKind.String),
            new(3, "asset_code"u8.ToArray(), ColumnKind.String),
            new(4, "mid_price"u8.ToArray(), ColumnKind.Double),
            new(5, "micro_price"u8.ToArray(), ColumnKind.Double),
            new(6, "spread_l1"u8.ToArray(), ColumnKind.Double),
            new(7, "spread_l2"u8.ToArray(), ColumnKind.Double),
            new(8, "spread_l3"u8.ToArray(), ColumnKind.Double),
            new(9, "spread_l5"u8.ToArray(), ColumnKind.Double),
            new(10, "spread_l10"u8.ToArray(), ColumnKind.Double),
            new(11, "spread_l20"u8.ToArray(), ColumnKind.Double),
            new(12, "levels_b"u8.ToArray(), ColumnKind.Int32),
            new(13, "levels_s"u8.ToArray(), ColumnKind.Int32),
            new(14, "vol_b_l1"u8.ToArray(), ColumnKind.Int64),
            new(15, "vol_b_l2"u8.ToArray(), ColumnKind.Int64),
            new(16, "vol_b_l3"u8.ToArray(), ColumnKind.Int64),
            new(17, "vol_b_l5"u8.ToArray(), ColumnKind.Int64),
            new(18, "vol_b_l10"u8.ToArray(), ColumnKind.Int64),
            new(19, "vol_b_l20"u8.ToArray(), ColumnKind.Int64),
            new(20, "vol_s_l1"u8.ToArray(), ColumnKind.Int64),
            new(21, "vol_s_l2"u8.ToArray(), ColumnKind.Int64),
            new(22, "vol_s_l3"u8.ToArray(), ColumnKind.Int64),
            new(23, "vol_s_l5"u8.ToArray(), ColumnKind.Int64),
            new(24, "vol_s_l10"u8.ToArray(), ColumnKind.Int64),
            new(25, "vol_s_l20"u8.ToArray(), ColumnKind.Int64),
            new(26, "vwap_b_l3"u8.ToArray(), ColumnKind.Double),
            new(27, "vwap_b_l5"u8.ToArray(), ColumnKind.Double),
            new(28, "vwap_b_l10"u8.ToArray(), ColumnKind.Double),
            new(29, "vwap_b_l20"u8.ToArray(), ColumnKind.Double),
            new(30, "vwap_s_l3"u8.ToArray(), ColumnKind.Double),
            new(31, "vwap_s_l5"u8.ToArray(), ColumnKind.Double),
            new(32, "vwap_s_l10"u8.ToArray(), ColumnKind.Double),
            new(33, "vwap_s_l20"u8.ToArray(), ColumnKind.Double),
            new(34, "SYSTIME"u8.ToArray(), ColumnKind.DateTime),
        ],
        Table = "moex_ob_stats_5m_futures",
        TargetColumns =
        [
            new("secid", "LowCardinality(String)", FillRule.TaskSecId, Required: true,
                RequiredMessage: "Загрузка статистики стакана отвергнута: secid пустой."),
            new("source_time", "DateTime64(3, 'Europe/Moscow')", FillRule.SourceDateTime, 0, 1, Required: true),
            new("asset_code", "LowCardinality(Nullable(String))", FillRule.Direct, 3),
            new("mid_price", "Nullable(Float64)", FillRule.Direct, 4),
            new("micro_price", "Nullable(Float64)", FillRule.Direct, 5),
            new("spread_l1", "Nullable(Float64)", FillRule.Direct, 6),
            new("spread_l2", "Nullable(Float64)", FillRule.Direct, 7),
            new("spread_l3", "Nullable(Float64)", FillRule.Direct, 8),
            new("spread_l5", "Nullable(Float64)", FillRule.Direct, 9),
            new("spread_l10", "Nullable(Float64)", FillRule.Direct, 10),
            new("spread_l20", "Nullable(Float64)", FillRule.Direct, 11),
            new("levels_b", "Nullable(Int32)", FillRule.Direct, 12),
            new("levels_s", "Nullable(Int32)", FillRule.Direct, 13),
            new("vol_b_l1", "Nullable(Int64)", FillRule.Direct, 14),
            new("vol_b_l2", "Nullable(Int64)", FillRule.Direct, 15),
            new("vol_b_l3", "Nullable(Int64)", FillRule.Direct, 16),
            new("vol_b_l5", "Nullable(Int64)", FillRule.Direct, 17),
            new("vol_b_l10", "Nullable(Int64)", FillRule.Direct, 18),
            new("vol_b_l20", "Nullable(Int64)", FillRule.Direct, 19),
            new("vol_s_l1", "Nullable(Int64)", FillRule.Direct, 20),
            new("vol_s_l2", "Nullable(Int64)", FillRule.Direct, 21),
            new("vol_s_l3", "Nullable(Int64)", FillRule.Direct, 22),
            new("vol_s_l5", "Nullable(Int64)", FillRule.Direct, 23),
            new("vol_s_l10", "Nullable(Int64)", FillRule.Direct, 24),
            new("vol_s_l20", "Nullable(Int64)", FillRule.Direct, 25),
            new("vwap_b_l3", "Nullable(Float64)", FillRule.Direct, 26),
            new("vwap_b_l5", "Nullable(Float64)", FillRule.Direct, 27),
            new("vwap_b_l10", "Nullable(Float64)", FillRule.Direct, 28),
            new("vwap_b_l20", "Nullable(Float64)", FillRule.Direct, 29),
            new("vwap_s_l3", "Nullable(Float64)", FillRule.Direct, 30),
            new("vwap_s_l5", "Nullable(Float64)", FillRule.Direct, 31),
            new("vwap_s_l10", "Nullable(Float64)", FillRule.Direct, 32),
            new("vwap_s_l20", "Nullable(Float64)", FillRule.Direct, 33),
            new("systime", "Nullable(DateTime64(3, 'Europe/Moscow'))", FillRule.WallClock, 34),
        ],
        TokenPrefix = "obstats:5m:futures",
        Pagination = PaginationKind.Cursor,
        RequestKey = RequestKeyRule.TaskSecId,
    };

    public static readonly MoexSeriesSpec OrderStatsStock = new()
    {
        DataKind = "orderstats",
        Market = "stock",
        TelemetryDataKind = "orderstats",
        MethodTemplate = "/datashop/algopack/eq/orderstats/{0}.json",
        RootKey = "data",
        SourceColumns =
        [
            new(0, "tradedate"u8.ToArray(), ColumnKind.String),
            new(1, "tradetime"u8.ToArray(), ColumnKind.String),
            new(2, "secid"u8.ToArray(), ColumnKind.String),
            new(3, "put_orders_b"u8.ToArray(), ColumnKind.Int32),
            new(4, "put_orders_s"u8.ToArray(), ColumnKind.Int32),
            new(5, "put_val_b"u8.ToArray(), ColumnKind.Double),
            new(6, "put_val_s"u8.ToArray(), ColumnKind.Double),
            new(7, "put_vol_b"u8.ToArray(), ColumnKind.Int32),
            new(8, "put_vol_s"u8.ToArray(), ColumnKind.Int32),
            new(9, "put_vwap_b"u8.ToArray(), ColumnKind.Double),
            new(10, "put_vwap_s"u8.ToArray(), ColumnKind.Double),
            new(11, "put_vol"u8.ToArray(), ColumnKind.Int32),
            new(12, "put_val"u8.ToArray(), ColumnKind.Double),
            new(13, "put_orders"u8.ToArray(), ColumnKind.Int32),
            new(14, "cancel_orders_b"u8.ToArray(), ColumnKind.Int32),
            new(15, "cancel_orders_s"u8.ToArray(), ColumnKind.Int32),
            new(16, "cancel_val_b"u8.ToArray(), ColumnKind.Double),
            new(17, "cancel_val_s"u8.ToArray(), ColumnKind.Double),
            new(18, "cancel_vol_b"u8.ToArray(), ColumnKind.Int32),
            new(19, "cancel_vol_s"u8.ToArray(), ColumnKind.Int64),
            new(20, "cancel_vwap_b"u8.ToArray(), ColumnKind.Double),
            new(21, "cancel_vwap_s"u8.ToArray(), ColumnKind.Double),
            new(22, "cancel_vol"u8.ToArray(), ColumnKind.Int64),
            new(23, "cancel_val"u8.ToArray(), ColumnKind.Double),
            new(24, "cancel_orders"u8.ToArray(), ColumnKind.Int64),
            new(25, "SYSTIME"u8.ToArray(), ColumnKind.DateTime),
        ],
        Table = "moex_order_stats_5m_stock",
        TargetColumns =
        [
            new("secid", "LowCardinality(String)", FillRule.TaskSecId, Required: true,
                RequiredMessage: "Загрузка статистики заявок отвергнута: secid пустой."),
            new("source_time", "DateTime64(3, 'Europe/Moscow')", FillRule.SourceDateTime, 0, 1, Required: true),
            new("put_orders_b", "Nullable(Int32)", FillRule.Direct, 3),
            new("put_orders_s", "Nullable(Int32)", FillRule.Direct, 4),
            new("put_val_b", "Nullable(Float64)", FillRule.Direct, 5),
            new("put_val_s", "Nullable(Float64)", FillRule.Direct, 6),
            new("put_vol_b", "Nullable(Int32)", FillRule.Direct, 7),
            new("put_vol_s", "Nullable(Int32)", FillRule.Direct, 8),
            new("put_vwap_b", "Nullable(Float64)", FillRule.Direct, 9),
            new("put_vwap_s", "Nullable(Float64)", FillRule.Direct, 10),
            new("put_vol", "Nullable(Int32)", FillRule.Direct, 11),
            new("put_val", "Nullable(Float64)", FillRule.Direct, 12),
            new("put_orders", "Nullable(Int32)", FillRule.Direct, 13),
            new("cancel_orders_b", "Nullable(Int32)", FillRule.Direct, 14),
            new("cancel_orders_s", "Nullable(Int32)", FillRule.Direct, 15),
            new("cancel_val_b", "Nullable(Float64)", FillRule.Direct, 16),
            new("cancel_val_s", "Nullable(Float64)", FillRule.Direct, 17),
            new("cancel_vol_b", "Nullable(Int32)", FillRule.Direct, 18),
            new("cancel_vol_s", "Nullable(Int64)", FillRule.Direct, 19),
            new("cancel_vwap_b", "Nullable(Float64)", FillRule.Direct, 20),
            new("cancel_vwap_s", "Nullable(Float64)", FillRule.Direct, 21),
            new("cancel_vol", "Nullable(Int64)", FillRule.Direct, 22),
            new("cancel_val", "Nullable(Float64)", FillRule.Direct, 23),
            new("cancel_orders", "Nullable(Int64)", FillRule.Direct, 24),
            new("systime", "Nullable(DateTime64(3, 'Europe/Moscow'))", FillRule.WallClock, 25),
        ],
        TokenPrefix = "orderstats:5m:stock",
        Pagination = PaginationKind.Cursor,
        RequestKey = RequestKeyRule.TaskSecId,
    };

    public static readonly MoexSeriesSpec Hi2Stock = new()
    {
        DataKind = "hi2",
        Market = "stock",
        TelemetryDataKind = "hi2",
        MethodTemplate = "/datashop/algopack/eq/hi2/{0}.json",
        RootKey = "data",
        SourceColumns =
        [
            new(0, "tradedate"u8.ToArray(), ColumnKind.String),
            new(1, "tradetime"u8.ToArray(), ColumnKind.String),
            new(2, "secid"u8.ToArray(), ColumnKind.String),
            new(3, "metric"u8.ToArray(), ColumnKind.String),
            new(4, "value"u8.ToArray(), ColumnKind.Double),
            new(5, "reference"u8.ToArray(), ColumnKind.String),
            new(6, "SYSTIME"u8.ToArray(), ColumnKind.DateTime),
        ],
        Table = "moex_hi2_daily_stock",
        TargetColumns =
        [
            new("secid", "LowCardinality(String)", FillRule.TaskSecId, Required: true,
                RequiredMessage: "Загрузка концентрации отвергнута: secid пустой."),
            new("source_time", "DateTime64(3, 'Europe/Moscow')", FillRule.SourceDateTime, 0, 1, Required: true),
            new("metric", "LowCardinality(String)", FillRule.Direct, 3, Required: true,
                RequiredMessage: "Строка концентрации отвергнута: metric пустой."),
            new("value", "Nullable(Float64)", FillRule.Direct, 4),
            new("reference", "Nullable(String)", FillRule.Direct, 5),
            new("systime", "Nullable(DateTime64(3, 'Europe/Moscow'))", FillRule.WallClock, 6),
        ],
        TokenPrefix = "hi2:1d:stock",
        Pagination = PaginationKind.Cursor,
        RequestKey = RequestKeyRule.TaskSecId,
    };

    public static readonly MoexSeriesSpec Hi2Futures = new()
    {
        DataKind = "hi2",
        Market = "futures",
        TelemetryDataKind = "hi2",
        MethodTemplate = "/datashop/algopack/fo/hi2/{0}.json",
        RootKey = "data",
        SourceColumns =
        [
            new(0, "tradedate"u8.ToArray(), ColumnKind.String),
            new(1, "tradetime"u8.ToArray(), ColumnKind.String),
            new(2, "secid"u8.ToArray(), ColumnKind.String),
            new(3, "asset_code"u8.ToArray(), ColumnKind.String),
            new(4, "metric"u8.ToArray(), ColumnKind.String),
            new(5, "value"u8.ToArray(), ColumnKind.Double),
            new(6, "reference"u8.ToArray(), ColumnKind.String),
            new(7, "SYSTIME"u8.ToArray(), ColumnKind.DateTime),
        ],
        Table = "moex_hi2_daily_futures",
        TargetColumns =
        [
            new("secid", "LowCardinality(String)", FillRule.TaskSecId, Required: true,
                RequiredMessage: "Загрузка концентрации отвергнута: secid пустой."),
            new("source_time", "DateTime64(3, 'Europe/Moscow')", FillRule.SourceDateTime, 0, 1, Required: true),
            new("asset_code", "LowCardinality(Nullable(String))", FillRule.Direct, 3),
            new("metric", "LowCardinality(String)", FillRule.Direct, 4, Required: true,
                RequiredMessage: "Строка концентрации отвергнута: metric пустой."),
            new("value", "Nullable(Float64)", FillRule.Direct, 5),
            new("reference", "Nullable(String)", FillRule.Direct, 6),
            new("systime", "Nullable(DateTime64(3, 'Europe/Moscow'))", FillRule.WallClock, 7),
        ],
        TokenPrefix = "hi2:1d:futures",
        Pagination = PaginationKind.Cursor,
        RequestKey = RequestKeyRule.TaskSecId,
    };

    public static readonly MoexSeriesSpec MegaAlertsStock = new()
    {
        DataKind = "mega_alerts",
        Market = "stock",
        TelemetryDataKind = "alerts",
        MethodTemplate = "/datashop/algopack/eq/alerts/{0}.json",
        RootKey = "data",
        SourceColumns =
        [
            new(0, "tradedate"u8.ToArray(), ColumnKind.String),
            new(1, "tradetime"u8.ToArray(), ColumnKind.String),
            new(2, "secid"u8.ToArray(), ColumnKind.String),
            new(3, "alert_type"u8.ToArray(), ColumnKind.String),
            new(4, "threshold"u8.ToArray(), ColumnKind.Double),
            new(5, "value"u8.ToArray(), ColumnKind.Double),
            new(6, "reference"u8.ToArray(), ColumnKind.String),
            new(7, "SYSTIME"u8.ToArray(), ColumnKind.DateTime),
        ],
        Table = "moex_megaalerts_stock",
        TargetColumns =
        [
            new("secid", "LowCardinality(String)", FillRule.TaskSecId, Required: true,
                RequiredMessage: "Загрузка мегаалёртов отвергнута: secid пустой."),
            new("source_time", "DateTime64(3, 'Europe/Moscow')", FillRule.SourceDateTime, 0, 1, Required: true),
            new("alert_type", "LowCardinality(String)", FillRule.Direct, 3, Required: true,
                RequiredMessage: "Строка мегаалёртов отвергнута: alert_type пустой."),
            new("threshold", "Nullable(Float64)", FillRule.Direct, 4),
            new("value", "Nullable(Float64)", FillRule.Direct, 5),
            new("reference", "Nullable(String)", FillRule.Direct, 6),
            new("systime", "Nullable(DateTime64(3, 'Europe/Moscow'))", FillRule.WallClock, 7),
        ],
        TokenPrefix = "megaalerts:event:stock",
        Pagination = PaginationKind.Cursor,
        RequestKey = RequestKeyRule.TaskSecId,
    };

    public static readonly MoexSeriesSpec MegaAlertsFutures = new()
    {
        DataKind = "mega_alerts",
        Market = "futures",
        TelemetryDataKind = "alerts",
        MethodTemplate = "/datashop/algopack/fo/alerts/{0}.json",
        RootKey = "data",
        SourceColumns =
        [
            new(0, "tradedate"u8.ToArray(), ColumnKind.String),
            new(1, "tradetime"u8.ToArray(), ColumnKind.String),
            new(2, "secid"u8.ToArray(), ColumnKind.String),
            new(3, "asset_code"u8.ToArray(), ColumnKind.String),
            new(4, "alert_type"u8.ToArray(), ColumnKind.String),
            new(5, "threshold"u8.ToArray(), ColumnKind.Double),
            new(6, "value"u8.ToArray(), ColumnKind.Double),
            new(7, "reference"u8.ToArray(), ColumnKind.String),
            new(8, "SYSTIME"u8.ToArray(), ColumnKind.DateTime),
        ],
        Table = "moex_megaalerts_futures",
        TargetColumns =
        [
            new("secid", "LowCardinality(String)", FillRule.TaskSecId, Required: true,
                RequiredMessage: "Загрузка мегаалёртов отвергнута: secid пустой."),
            new("source_time", "DateTime64(3, 'Europe/Moscow')", FillRule.SourceDateTime, 0, 1, Required: true),
            new("asset_code", "LowCardinality(Nullable(String))", FillRule.Direct, 3),
            new("alert_type", "LowCardinality(String)", FillRule.Direct, 4, Required: true,
                RequiredMessage: "Строка мегаалёртов отвергнута: alert_type пустой."),
            new("threshold", "Nullable(Float64)", FillRule.Direct, 5),
            new("value", "Nullable(Float64)", FillRule.Direct, 6),
            new("reference", "Nullable(String)", FillRule.Direct, 7),
            new("systime", "Nullable(DateTime64(3, 'Europe/Moscow'))", FillRule.WallClock, 8),
        ],
        TokenPrefix = "megaalerts:event:futures",
        Pagination = PaginationKind.Cursor,
        RequestKey = RequestKeyRule.TaskSecId,
    };
}
